### ISSUE TITLE
ir-resnet.py中resnet函数调用

### ISSUE THREAD

**Issue by universewill** [shuokay/mxnet-ir#2]
我在运行时，发现ir-resnet.py中get_network函数调用了resnet函数。

我在网上找到了这个版本:https://github.com/tornadomeet/ResNet/blob/master/symbol_resnet.py

但是这里的resnet参数跟你的调用不符。你的调用中多了data参数
请问这个resnet的代码哪里可以找到？

非常感谢你的博客与源码，受益颇多，谢谢！

**Comment by shuokay** [comment]
https://github.com/tornadomeet/ResNet/blob/master/symbol_resnet.py#L85
自己构建一个 variable 传进去就好了

**Comment by universewill** [comment]
我删除了resnet函数中https://github.com/tornadomeet/ResNet/blob/master/symbol_resnet.py#L85的data variable，并把
concat = mx.symbol.Concat(*[anchor, positive, negative], dim=0, name="concat")作为data variable传递进入resnet函数，现在程序报错如下：

Traceback (most recent call last):
  File "/Users/nali/PycharmProjects/mxnet-ir/test.py", line 105, in <module>
    test_train()
  File "/Users/nali/PycharmProjects/mxnet-ir/test.py", line 101, in test_train
    epoch_end_callback=mx.callback.do_checkpoint("models/ir-blur"))
  File "/Library/Python/2.7/site-packages/mxnet/model.py", line 782, in fit
    self._init_params(data.provide_data+data.provide_label)
  File "/Library/Python/2.7/site-packages/mxnet/model.py", line 526, in _init_params
    self.initializer(k, v)
  File "/Library/Python/2.7/site-packages/mxnet/initializer.py", line 259, in __call__
    self.param[name].shape)
AssertionError: Parameter fc1_bias cannot be initialized from loading. Shape mismatch, target (128L,) vs loaded (1000L,)

请问是怎么产生的错误？

**Comment by shuokay** [comment]
` Parameter fc1_bias cannot be initialized from loading. Shape mismatch, target (128L,) vs loaded (1000L,)`
维数不匹配, 检查你代码的维数. graph 要求是 128, 你给的是1000

**Comment by universewill** [comment]
应该是这样。
我的resnet-18-0000.params文件是这里下载的：http://data.dmlc.ml/mxnet/models/imagenet/resnet/
可能预测的分类数目为1000.
你的代码里num_class是128，你的resnet-18-0000.params文件是自己处理过的么？

**Comment by shuokay** [comment]
不需要 `softmax` layer,  改成 `L2Normalization`

**Comment by txsniper** [comment]
# @universewill 
hi，维度数量不匹配这个问题你怎么解决的？
