### ISSUE TITLE
ValueError: Unknown initialization pattern for softmax_label

### ISSUE THREAD

**Issue by universewill** [shuokay/mxnet-ir#3]
程序在运行时报了这个错误：

/Users/nali/PycharmProjects/mxnet-ir/test.py:96: DeprecationWarning: mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
  optimizer=optimizer)
/Library/Python/2.7/site-packages/mxnet/initializer.py:267: DeprecationWarning: Calling initializer with init(str, NDArray) has been deprecated.please use init(mx.init.InitDesc(...), NDArray) instead.
  self.default_init(name, arr)
Traceback (most recent call last):
  File "/Users/nali/PycharmProjects/mxnet-ir/test.py", line 105, in <module>
    test_train()
  File "/Users/nali/PycharmProjects/mxnet-ir/test.py", line 101, in test_train
    epoch_end_callback=mx.callback.do_checkpoint("models/ir-blur"))
  File "/Library/Python/2.7/site-packages/mxnet/model.py", line 782, in fit
    self._init_params(data.provide_data+data.provide_label)
  File "/Library/Python/2.7/site-packages/mxnet/model.py", line 526, in _init_params
    self.initializer(k, v)
  File "/Library/Python/2.7/site-packages/mxnet/initializer.py", line 267, in __call__
    self.default_init(name, arr)
  File "/Library/Python/2.7/site-packages/mxnet/initializer.py", line 72, in __call__
    self._legacy_init(desc, arr)
  File "/Library/Python/2.7/site-packages/mxnet/initializer.py", line 138, in _legacy_init
    self._init_default(name, arr)
  File "/Library/Python/2.7/site-packages/mxnet/initializer.py", line 180, in _init_default
    'Please use mx.sym.Variable(init=mx.init.*) to set initialization pattern' % name)
ValueError: Unknown initialization pattern for softmax_label. Default initialization is now limited to "weight", "bias", "gamma" (1.0), and "beta" (0.0).Please use mx.sym.Variable(init=mx.init.*) to set initialization pattern

**Comment by universewill** [comment]
我将get_network的结果使用mx.viz.plot_network进行查看，截图为plot的最后部分。可以看到里面有个softmax_label模块。根据你的博客内容，我的理解是，share_net里面应该是不包含softmax模块的。应
请问 D.其他层 是指什么层？是tripletloss模块跟flatten0之间的层么？

<img width="350" alt="2017-06-25 11 39 04" src="https://user-images.githubusercontent.com/6790730/27513504-f515dee8-599a-11e7-8059-720394a4373b.png">

我更改了网络结构，flatten0直接连结到tripletloss网络，运行时报了这个错误：
infer_shape error. Arguments:
  positive: (16, 3, 224, 224)
  one: (16,)
  anchor: (16, 3, 224, 224)
  negative: (16, 3, 224, 224)

更改后的网络：
<img width="392" alt="2017-06-25 12 18 40" src="https://user-images.githubusercontent.com/6790730/27513641-7d683ca0-59a0-11e7-82fb-039124b8d044.png">

**Comment by universewill** [comment]
This error disappears when use only one cpu/gpu.
refer to this https://github.com/dmlc/mxnet/issues/6806

**Comment by Light--** [comment]
> This error disappears when use only one cpu/gpu.

but i need to use multi-gpus, how to fix that ?
